# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-added-large-files
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.77.1
  hooks:
    - id: terraform_docs
      args:
      - --hook-config=--path-to-file=README.md
      - --hook-config=--add-to-existing-file=false
      - --hook-config=--create-file-if-not-exist=true
    - id: terraform_fmt
    - id: terraform_validate
